apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: system:podsecuritypolicy:fluentd-gcp
  namespace: kube-system
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
rules:
- apiGroups:
  - extensions
  resourceNames:
  - system.fluentd-gcp
  resources:
  - podsecuritypolicies
  verbs:
  - use
