apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: restricted-v1
  annotations:
    kubernetes.io/description: 'This policy demonstrates best practices for
      running Pods with minimal security priviliges.'
    # To use custom seccomp or apparmor profiles, make a copy of this policy and
    # add the custom profiles here.
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: 'docker/default'
    apparmor.security.beta.kubernetes.io/allowedProfileNames: 'runtime/default'
    # WARNING: PodSecurityPolicy ordering is not (yet) well defined, so if
    # multiple policies match, default application is unpredictable. To avoid
    # potential problems, either ensure that defaults are consistent across
    # policies or that only a single policy can match a given Pod.
    seccomp.security.alpha.kubernetes.io/defaultProfileName:  'docker/default'
    apparmor.security.beta.kubernetes.io/defaultProfileName:  'runtime/default'
  labels:
    kubernetes.io/cluster-service: 'true'
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  privileged: false
  allowPrivilegeEscalation: false
  volumes:
  - 'configMap'
  - 'emptyDir'
  - 'persistentVolumeClaim'
  - 'projected'
  - 'secret'
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: 'MustRunAsNonRoot'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'RunAsAny'
  readOnlyRootFilesystem: false
