apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: restricted
  annotations:
    kubernetes.io/description: 'restricted allows minimal access for create pods to work.'
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: EnsureExists
spec:
  privileged: false
  hostIPC: false
  hostPID: false
  hostNetwork: false
  fsGroup:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - 'azureFile'
  - 'flocker'
  - 'flexVolume'
  - 'emptyDir'
  - 'gcePersistentDisk'
  - 'awsElasticBlockStore'
  - 'gitRepo'
  - 'secret'
  - 'nfs'
  - 'iscsi'
  - 'glusterfs'
  - 'persistentVolumeClaim'
  - 'rbd'
  - 'cinder'
  - 'cephFS'
  - 'downwardAPI'
  - 'fc'
  - 'configMap'
  - 'vsphereVolume'
  - 'quobyte'
  - 'azureDisk'
  - 'photonPersistentDisk'
  - 'storageos'
  - 'projected'
  - 'portworxVolume'
  - 'scaleIO'
