apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: podsecuritypolicy:restricted
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: EnsureExists
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: podsecuritypolicy:restricted
subjects:
- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: Group
  name: system:authenticated
