apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: gce.metadata-agent
  annotations:
    kubernetes.io/description: 'Policy used by the metadata-agent addon.'
    seccomp.security.alpha.kubernetes.io/defaultProfileName:  'docker/default'
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: 'runtime/default,docker/default'
    # 'runtime/default' is already the default, but must be filled in on the
    # pod to pass admission.
    apparmor.security.beta.kubernetes.io/defaultProfileName:  'runtime/default'
    apparmor.security.beta.kubernetes.io/allowedProfileNames: 'runtime/default'
  labels:
    kubernetes.io/cluster-service: 'true'
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  privileged: false
  allowPrivilegeEscalation: false
  volumes:
  - 'emptyDir'
  - 'configMap'
  - 'secret'
  - 'projected'
  hostNetwork: false
  hostIPC: false
  hostPID: false
  hostPorts:
  - min: 8799
    max: 8799
  # TODO: The addons using this profile should not run as root.
  runAsUser:
    rule: 'RunAsAny'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'RunAsAny'
  readOnlyRootFilesystem: false
