apiVersion: v1
kind: Pod
metadata:
  name: webhook-test
  labels:
    test: admission-webhook
spec:
  containers:
  - name: webhook
    image: gcr.io/stclair-k8s-ext/webhook-test:latest
    command:
      - /webhook
      - -cert=/certs/tls.crt
      - -key=/certs/tls.key
    imagePullPolicy: Always
    volumeMounts:
      - name: certs
        mountPath: /certs
        readOnly: true
  volumes:
    - name: certs
      secret:
        secretName: webhook-certs
