apiVersion: v1
kind: Pod
metadata:
  name: admission-webhook
  labels:
    test: admission-webhook
spec:
  containers:
  - name: webhook
    image: gcr.io/stclair-k8s-ext/webhook-test:latest
---
apiVersion: v1
kind: Service
metadata:
  name: admission-webhook-test
spec:
  selector:
    test: admission-webhook
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: webhook-test
webhooks:
  - name: test.example.com
    rules:
      - operations: ["*"]
        apiGroups: ["*"]
        apiVersions: ["*"]
        resources: ["*"]
    clientConfig:
      service:
        namespace: default
        name: admission-webhook-test
      caBundle: ""
